name: CICD Pipeline

on:
  push:
    branches:
      - main

env:
  APP_NAME: 'profile-app'
  DOCKER_HUB_USERNAME: 'troybarrett8362'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }} .

      - name: Tag Docker image
        run: docker tag ${{ env.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:latest ${{ env.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}

  base-test:
    runs-on: ubuntu-latest
    needs: build-and-publish
    container:
      image: docker:27.0.2-cli-alpine3.20
      options: --privileged
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Pull MongoDB image
        run: docker pull mongo:8.0-rc

      - name: Create Docker network
        run: docker network create mongo-network

      - name: Run MongoDB container
        run: |
          docker run -d --network mongo-network --name mongoDB -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=secret mongo:8.0-rc

      - name: Run application container
        run: |
          docker run -d --network mongo-network --name ${{ env.APP_NAME }} -p 3000:3000 -e MONGO_PASS=secret -e MONGO_HOST=mongoDB ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Show running containers
        run: docker ps -a

      - name: Show MongoDB container logs
        run: docker logs mongoDB

      - name: Show application logs
        run: docker logs ${{ env.APP_NAME }}

      - name: Install curl
        run: apk add --no-cache curl

      - name: Check network connectivity to app container
        run: docker exec ${{ env.APP_NAME }} ping -c 4 ${{ env.APP_NAME }}

      - name: Wait for app to start
        run: docker exec ${{ env.APP_NAME }} curl -f http://localhost:3000 || exit 1

      - name: Test application
        run: curl http://${{ env.APP_NAME }}:3000 | grep 'User profile'
